token: "LICHESS_TOKEN_HERE"

url: "https://lichess.org"

engine:
  dir: "/Users/mateichiriac/Documents/chess-engine"
  name: "run_engine.sh"
  protocol: uci
  silence_stderr: false

  uci_options:
    Threads: 1

abort_time: 20
move_overhead: 500
online_moves:
  sources: []

matchmaking:
  allow_matchmaking: true
  challenge_timeout: 30
  challenge_initial_time:
    - 60
    - 180
    - 300
  challenge_increment:
    - 0
    - 1
    - 2
  opponent_min_rating: 800
  opponent_max_rating: 3000
  rating_preference: "none"
  challenge_variant: "standard"
  challenge_mode: "rated"

challenge:
  concurrency: 1
  sort_by: "best"
  accept_bot: true
  only_bot: false
  min_increment: 0
  max_increment: 180
  min_base: 0
  max_base: 3600
  variants:
    - standard
  time_controls:
    - bullet
    - blitz
    - rapid
  modes:
    - casual
    - rated
